### ISSUE TITLE
wait-on command is not found when running local.sh start

### ISSUE THREAD

**Issue by ItWorks0nMyMachine** [alek-sys/animal-rescue-tdd#1]
When running on Mac Os Catalina 10.15.7 once cloned from main branch ([commit](https://github.com/alek-sys/animal-rescue-tdd/commit/68d42081936f0c655edd62a676ea7ec93d312be9))
``` 
➜  testfirst-workshop git:(main) ./scripts/local.sh start

======== Starting backend ========

======== Starting frontend ========

Welcome to Gradle 6.5!

Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples

For more details see https://docs.gradle.org/6.5/release-notes.html

> frontend@1.0.0 start
> wait-on tcp:8080 && REACT_APP_LOGIN_URI=http://localhost:8080/login REACT_APP_LOGOUT_URI=http://localhost:8080/logout react-scripts start

sh: wait-on: command not found
npm ERR! code 127
npm ERR! path /sandbox/jocker2020/testfirst-workshop/frontend
npm ERR! command failed
npm ERR! command sh -c wait-on tcp:8080 && REACT_APP_LOGIN_URI=http://localhost:8080/login REACT_APP_LOGOUT_URI=http://localhost:8080/logout react-scripts start

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-11-26T23_34_34_572Z-debug.log

```

Expected: wait-on is installed as a local npm dependency module and front-end successfully starts
Observed: front-end fails to start

**Comment by ItWorks0nMyMachine** [comment]
Seems to be a documentation issue as after `/scripts/local.sh init` ahead of `./scripts/local.sh start` everything works perfectly

**Comment by alek-sys** [comment]
Thanks for reporting, you are right - `./scripts/local.sh init` is mandatory. I'm using this repo as a demonstration for my TDD workshop so I'm going to talk it thought, feel free to update README if you find it useful.
